[build]
  command = "npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NEXT_PUBLIC_SITE_URL = "https://plant-identification-app.netlify.app"
  APP_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true
